name: Scrape Table Sums

on:
  push:
    branches: [main]

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (23f1002057@ds.study.iitm.ac.in)
        run: npm install

      - name: Install Playwright (browsers + dependencies)
        uses: microsoft/playwright-github-action@v1

      - name: Run Playwright Scraper
        run: npm run scrape
